---
- name: Patch cutover on latest Migration for each Plan from Survey input
  hosts: localhost
  gather_facts: false

  vars:
    csv_file: "vm_list_to_migrate.csv"
    mtv_namespace: "openshift-mtv"
    survey_input_plan_names: "{{ survey_plan_names | default('') }}"
    plan_names: "{{ survey_input_plan_names.split(',') | map('trim') | list }}"

  tasks:
    - name: Read and parse the CSV file
      community.general.read_csv:
        path: "{{ csv_file }}"
      register: vm_list

    - name: Filter VM data based on group names
      set_fact:
        filtered_vms: >
          {{
            vm_list.list | selectattr('GM Cutover Sequence', 'in', plan_names) | list
          }}

    - name: Extract the unique plan names from filtered VM data
      set_fact:
        filtered_plans: "{{ filtered_vms | map(attribute='Plan Name') | unique | list }}"

    - name: Get all Migration CRs in the namespace
      kubernetes.core.k8s_info:
        api_version: forklift.konveyor.io/v1beta1
        kind: Migration
        namespace: "{{ mtv_namespace }}"
      register: all_migrations

    - name: Calculate cutover time (UTC + 60 seconds)
      set_fact:
        cutover_time: "{{ lookup('pipe', 'date -u -d \"+60 seconds\" +\"%Y-%m-%dT%H:%M:%SZ\"') }}"

    - name: Cutover each plan using block task
      include_tasks: 03_2_patch_cutover_task.yml
      loop: "{{ filtered_plans }}"
      loop_control:
        loop_var: plan_name
