---
- name: Check reachability of VMs using TCP ports (22 for Linux, 3389 for Windows)
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"  # From survey
    os_type: "{{ os_type | default('linux') }}"  # From survey
    ping_results: []

  tasks:
    - name: Convert IPs to an array
      set_fact:
        ip_array: "{{ ip_list.split(',') | map('trim') | list }}"

    - name: Check reachability per IP (include task)
      include_tasks: 04_2_check_single_ip.yml
      loop: "{{ ip_array }}"
      loop_control:
        loop_var: current_ip
      vars:
        os_type: "{{ os_type }}"  # Passing the os_type dynamically for each IP

    - name: Format results into table
      set_fact:
        formatted_output: >-
          {%- set header = "| IP Address      | Ping Status |" -%}
          {%- set separator = "|------------------|-------------|" -%}
          {%- set rows = [] -%}
          {%- for item in ping_results -%}
          {%-   set _ = rows.append("| " ~ item.ip.ljust(16) ~ " | " ~ item.status.center(11) ~ " |") -%}
          {%- endfor -%}
          {{ ([header, separator] + rows) | join('\n') }}

    - name: Display formatted reachability table
      debug:
        msg: "{{ formatted_output }}"
