---
- name: Check reachability of VMs using TCP ports (22 for Linux, 3389 for Windows)
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    ping_results: []

  tasks:
    - name: Check reachability per IP (include task)
      include_tasks: 04_2_check_single_ip.yml
      loop: "{{ ip_array }}"
      loop_control:
        loop_var: current_ip

    - name: Format results into table
      set_fact:
        formatted_output: >-
          {%- set header = "| IP Address      | Ping Status |" -%}
          {%- set separator = "|------------------|-------------|" -%}
          {%- set rows = [] -%}
          {%- for item in ping_results -%}
          {%-   set _ = rows.append("| " ~ item.ip.ljust(15) ~ " | " ~ item.status.center(11) ~ " |") -%}
          {%- endfor -%}
          {{ ([header, separator] + rows) | join('\n') }}

    - name: Display formatted reachability table
      debug:
        var: formatted_output

    - name: Save formatted output as artifact
      set_stats:
        data:
          reachability_table: "{{ formatted_output }}"
        per_host: false

