---
- name: Check reachability of VMs on ports 22 and 3389
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"  # From survey
    ping_results: []

  tasks:
    - name: Convert IPs to an array
      set_fact:
        ip_array: "{{ ip_list.split(',') | map('trim') | list }}"

    - name: Check reachability per IP (include task)
      include_tasks: 04_2_check_single_ip.yml
      loop: "{{ ip_array }}"
      loop_control:
        loop_var: current_ip

    - name: Format results into table
      set_fact:
        formatted_output: >-
          {%- set header = "| IP Address      | Port 22 | Port 3389 |" -%}
          {%- set separator = "|------------------|---------|-----------|" -%}
          {%- set rows = [] -%}
          {%- for item in ping_results -%}
          {%-   set row = "| " ~ item.ip.ljust(16) ~ " | " ~ item.port22_status.center(7) ~ " | " ~ item.port3389_status.center(9) ~ " |" -%}
          {%-   set _ = rows.append(row) -%}
          {%- endfor -%}
          {{ ([header, separator] + rows) | join('\n') }}

    - name: Display formatted reachability table
      debug:
        msg: "{{ formatted_output }}"
