---
- name: Check reachability of VMs using TCP ports (22 for Linux, 3389 for Windows)
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"  # From the Survey
    os_type: "{{ os_type | default('linux') }}"  # From the Survey (linux/windows)
    ping_results: []

  tasks:
    - name: Convert IPs to an array
      set_fact:
        ip_array: "{{ ip_list.split(',') | map('trim') | list }}"

    - name: Check connectivity based on OS type
      block:
        - name: Check SSH (22) reachability for Linux VMs
          wait_for:
            host: "{{ item }}"
            port: 22
            timeout: 5
            state: started
          register: ssh_result
          when: os_type == 'linux'
          ignore_errors: true

        - name: Check RDP (3389) reachability for Windows VMs
          wait_for:
            host: "{{ item }}"
            port: 3389
            timeout: 5
            state: started
          register: rdp_result
          when: os_type == 'windows'
          ignore_errors: true

        - name: Append current result to ping_results
          set_fact:
            ping_results: "{{ ping_results + [ {
              'ip': item,
              'status': ((ssh_result is succeeded and os_type == 'linux') or (rdp_result is succeeded and os_type == 'windows')) | ternary('✅', '❌')
            } ] }}"
      loop: "{{ ip_array }}"

    - name: Format results into table
      set_fact:
        formatted_output: >-
          {%- set header = "| IP Address      | Ping Status |" -%}
          {%- set separator = "|------------------|-------------|" -%}
          {%- set rows = [] -%}
          {%- for item in ping_results -%}
          {%-   set _ = rows.append("| " ~ item.ip.ljust(16) ~ " | " ~ item.status.center(11) ~ " |") -%}
          {%- endfor -%}
          {{ ([header, separator] + rows) | join('\n') }}

    - name: Display formatted reachability table
      debug:
        msg: "{{ formatted_output }}"
