- name: Create Forklift migration plan with mappings
  hosts: localhost
  gather_facts: no

  vars:
    kubeconfig_path: ~/.kube/config  # Update this path
    namespace: openshift-mtv
    network_map_name: vmware-test-4
    storage_map_name: vmware-test-4
    migration_plan_name: test-4

  tasks:
    - name: Create NetworkMap
      copy:
        dest: /tmp/network-map.yaml
        content: |
          apiVersion: forklift.konveyor.io/v1beta1
          kind: NetworkMap
          metadata:
            name: "{{ network_map_name }}"
            namespace: "{{ namespace }}"
          spec:
            map:
              - source:
                  type: vmware
                  id: "CPMS-External"  # <-- Replace with actual VMware network ID
                destination:
                  type: pod
                  namespace: "{{ namespace }}"
                  name: "default/nad"        # <-- Replace with actual OpenShift network name
    - name: Apply NetworkMap
      shell: oc apply -f /tmp/network-map.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create StorageMap
      copy:
        dest: /tmp/storage-map.yaml
        content: |
          apiVersion: forklift.konveyor.io/v1beta1
          kind: StorageMap
          metadata:
            name: "{{ storage_map_name }}"
            namespace: "{{ namespace }}"
          spec:
            map:
              - source:
                  type: vmware
                  id: "vmware_datastores"   # <-- Replace with actual VMware datastore ID
                destination:
                  storageClass: "lvms-vg1"  # <-- Replace with your storage class
    - name: Apply StorageMap
      shell: oc apply -f /tmp/storage-map.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Create Migration Plan
      copy:
        dest: /tmp/migration-plan.yaml
        content: |
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Plan
          metadata:
            name: "{{ migration_plan_name }}"
            namespace: "{{ namespace }}"
          spec:
            archived: false
            description: ""
            map:
              network:
                name: "{{ network_map_name }}"
                namespace: "{{ namespace }}"
              storage:
                name: "{{ storage_map_name }}"
                namespace: "{{ namespace }}"
            provider:
              destination:
                name: host
                namespace: "{{ namespace }}"
              source:
                name: vmware
                namespace: "{{ namespace }}"
            targetNamespace: "{{ namespace }}"
            vms:
              - name: rhel-8
                hooks: []
            warm: true
            preserveStaticIPs: true
			migrateSharedDisks: true
    - name: Apply Migration Plan
      shell: oc apply -f /tmp/migration-plan.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
