---
- name: VM Migration Plan with manual CSV parsing (AAP compatible)
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yaml  # define your variables here: plan_name, mtv_namespace, source_provider_name, destination_provider_name, network_map_name, storage_map_name, target_network_namespace

  tasks:
    - name: Load raw CSV file as base64
      ansible.builtin.slurp:
        src: migration_plan.csv
      register: raw_csv

    - name: Decode CSV lines and filter empty
      set_fact:
        csv_lines: "{{ (raw_csv.content | b64decode).splitlines() | reject('equalto', '') | list }}"

    - name: Extract CSV header (list)
      set_fact:
        csv_header: "{{ csv_lines[0].split(',') | map('trim') | list }}"

    - name: Extract CSV data rows (list)
      set_fact:
        csv_data_rows: "{{ csv_lines[1:] }}"

    - name: Initialize parsed CSV list
      set_fact:
        parsed_csv: []

    - name: Parse CSV rows into list of dicts
      set_fact:
        parsed_csv: "{{ parsed_csv + [ dict(zip(csv_header, item.split(','))) ] }}"
      loop: "{{ csv_data_rows }}"

    - name: Debug parsed CSV content
      debug:
        var: parsed_csv

    - name: Build Forklift VM list from "RHOS Name" column
      set_fact:
        vm_list: "{{ parsed_csv | map(attribute='RHOS Name') | map('regex_replace', '^(.+)$', '{\"name\":\"\\1\"}') | map('from_json') | list }}"

    - name: Debug VM list
      debug:
        var: vm_list

    - name: Create Forklift Migration Plan
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Plan
          metadata:
            name: "{{ plan_name }}"
            namespace: "{{ mtv_namespace }}"
          spec:
            provider:
              source:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: Provider
                name: "{{ source_provider_name }}"
                namespace: "{{ mtv_namespace }}"
              destination:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: Provider
                name: "{{ destination_provider_name }}"
                namespace: "{{ mtv_namespace }}"
            map:
              network:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: NetworkMap
                name: "{{ network_map_name }}-{{ plan_name }}"
                namespace: "{{ mtv_namespace }}"
              storage:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: StorageMap
                name: "{{ storage_map_name }}-{{ plan_name }}"
                namespace: "{{ mtv_namespace }}"
            namespace: "{{ mtv_namespace }}"
            targetNamespace: "{{ mtv_namespace }}"
            vms: "{{ vm_list }}"
            warm: true
            preserveStaticIPs: true

    - name: Get Plan UID
      kubernetes.core.k8s_info:
        api_version: forklift.konveyor.io/v1beta1
        kind: Plan
        name: "{{ plan_name }}"
        namespace: "{{ mtv_namespace }}"
      register: plan_info

    - name: Set Plan UID fact
      set_fact:
        plan_uid: "{{ plan_info.resources[0].metadata.uid }}"

    - name: Create NetworkMap with owner reference
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: NetworkMap
          metadata:
            name: "{{ network_map_name }}-{{ plan_name }}"
            namespace: "{{ mtv_namespace }}"
            ownerReferences:
              - apiVersion: forklift.konveyor.io/v1beta1
                kind: Plan
                name: "{{ plan_name }}"
                uid: "{{ plan_uid }}"
                controller: true
                blockOwnerDeletion: true
          spec:
            provider:
              source:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: Provider
                name: "{{ source_provider_name }}"
                namespace: "{{ mtv_namespace }}"
              destination:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: Provider
                name: "{{ destination_provider_name }}"
                namespace: "{{ mtv_namespace }}"
            map:
              - source:
                  type: vmware
                  name: "{{ parsed_csv[0]['Source Network'] | default('') }}"
                destination:
                  type: multus
                  name: "{{ parsed_csv[0]['Target Network'] | default('') }}"
                  namespace: "{{ target_network_namespace }}"

    - name: Create StorageMap with owner reference
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: StorageMap
          metadata:
            name: "{{ storage_map_name }}-{{ plan_name }}"
            namespace: "{{ mtv_namespace }}"
            ownerReferences:
              - apiVersion: forklift.konveyor.io/v1beta1
                kind: Plan
                name: "{{ plan_name }}"
                uid: "{{ plan_uid }}"
                controller: true
                blockOwnerDeletion: true
          spec:
            provider:
              source:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: Provider
                name: "{{ source_provider_name }}"
                namespace: "{{ mtv_namespace }}"
              destination:
                apiVersion: forklift.konveyor.io/v1beta1
                kind: Provider
                name: "{{ destination_provider_name }}"
                namespace: "{{ mtv_namespace }}"
            map:
              - source:
                  type: vmware
                  name: "{{ parsed_csv[0]['Source Datastore'] | default('') }}"
                destination:
                  storageClass: "{{ parsed_csv[0]['Target StorageClass'] | default('') }}"
