---
- name: Start Cutover after DiskTransfer completes
  hosts: localhost
  gather_facts: no
  vars:
    migration_namespace: openshift-mtv
    migration_name: test-cutover13-migration-4lhz9
    vm_name: rhel-9
  tasks:

    - name: Get current migration resource
      command: >
        kubectl get migration {{ migration_name }} -n {{ migration_namespace }} -o json
      register: migration_json

    - name: Parse migration JSON
      set_fact:
        migration_data: "{{ migration_json.stdout | from_json }}"

    - name: Find DiskTransfer phase for VM {{ vm_name }}
      set_fact:
        disk_transfer_phase: >-
          {{
            migration_data.status.vms
            | selectattr('name', 'equalto', vm_name)
            | map(attribute='pipeline')
            | map('selectattr', 'name', 'equalto', 'DiskTransfer')
            | map('first')
            | map(attribute='phase')
            | first
          }}

    - name: Check if DiskTransfer phase is Completed
      debug:
        msg: "DiskTransfer phase is {{ disk_transfer_phase }}"
    
    - name: Fail if DiskTransfer not completed yet
      fail:
        msg: "DiskTransfer phase is not completed. Cannot start Cutover."
      when: disk_transfer_phase != "Completed"

    - name: Prepare patch to start Cutover
      set_fact:
        cutover_patch: |
          {
            "status": {
              "vms": [
                {
                  "name": "{{ vm_name }}",
                  "pipeline": [
                    {
                      "name": "Cutover",
                      "phase": "Running",
                      "started": "{{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%SZ') }}",
                      "progress": {
                        "completed": 1,
                        "total": 30720
                      },
                      "tasks": [
                        {
                          "name": "[vSAN-Datastore] 1b453068-0e51-116b-a94e-b8599f0581ac/rhel-9.vmdk",
                          "phase": "Running",
                          "started": "{{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%SZ') }}",
                          "progress": {
                            "completed": 1,
                            "total": 30720
                          }
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          }

    - name: Patch migration to start Cutover
      command: >
        kubectl patch migration {{ migration_name }} -n {{ migration_namespace }} --type=merge -p '{{ cutover_patch }}'
      register: patch_result

    - name: Show patch result
      debug:
        var: patch_result.stdout
