---
- name: Patch cutover on latest Migration for each Plan from Survey input
  hosts: localhost
  gather_facts: false

  vars:
    mtv_namespace: "openshift-mtv"
    user_input_plan_names: "{{ survey_plan_name | default('') }}"
    plan_names: "{{ user_input_plan_names.split(',') | map('trim') | list }}"

  tasks:
    - name: Get all Migration CRs in the namespace
      kubernetes.core.k8s_info:
        api_version: forklift.konveyor.io/v1beta1
        kind: Migration
        namespace: "{{ mtv_namespace }}"
      register: all_migrations

    - name: Calculate cutover time (UTC + 60 seconds)
      set_fact:
        cutover_time: "{{ lookup('pipe', 'date -u -d \"+60 seconds\" +\"%Y-%m-%dT%H:%M:%SZ\"') }}"

    - name: Patch latest migration with cutover time using include_tasks
      include_tasks: patch_cutover_block.yml
      loop: "{{ plan_names }}"
      loop_control:
        loop_var: plan_name
