---
- name: Cutover multiple migration plans from survey input
  hosts: localhost
  gather_facts: false

  vars_files:
    - vars.yaml  # Optional external vars

  vars:
    cutover_namespace: "{{ mtv_namespace }}"
    plan_names_list: "{{ plan_names.split(',') | map('trim') | list }}"

  tasks:
    - name: Validate that each plan exists
      kubernetes.core.k8s_info:
        api_version: forklift.konveyor.io/v1beta1
        kind: Plan
        name: "{{ item }}"
        namespace: "{{ cutover_namespace }}"
      register: plan_info
      failed_when: plan_info.resources | length == 0
      loop: "{{ plan_names_list }}"
      loop_control:
        loop_var: item

    - name: Start Cutover migration for each plan
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            generateName: "cutover-{{ item }}-"
            namespace: "{{ cutover_namespace }}"
          spec:
            cutover: "{{ lookup('ansible.builtin.date', '%Y-%m-%dT%H:%M:%SZ', utc=True) }}"
            plan:
              name: "{{ item }}"
              namespace: "{{ cutover_namespace }}"
      loop: "{{ plan_names_list }}"
      loop_control:
        loop_var: item
