- name: Cutover multiple migration plans from survey input
  hosts: localhost
  gather_facts: true

  vars_files:
    - vars.yaml

  vars:
    cutover_namespace: "{{ mtv_namespace }}"
    plan_names_list: "{{ plan_names.split(',') | map('trim') | list }}"

  tasks:
    - name: Validate that each plan exists
      kubernetes.core.k8s_info:
        api_version: forklift.konveyor.io/v1beta1
        kind: Plan
        name: "{{ item }}"
        namespace: "{{ cutover_namespace }}"
      register: plan_info
      failed_when: plan_info.resources | length == 0
      loop: "{{ plan_names_list }}"
      loop_control:
        loop_var: item

    - name: Start Cutover migration for each plan
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            generateName: "cutover-{{ item }}-"
            namespace: "{{ cutover_namespace }}"
          spec:
            cutover: "{{ ansible_date_time.iso8601 }}"
            plan:
              name: "{{ item }}"
              namespace: "{{ cutover_namespace }}"
      loop: "{{ plan_names_list }}"
      loop_control:
        loop_var: item
      register: migration_results

    - name: Resume cutover on each created Migration
      kubernetes.core.k8s:
        api_version: forklift.konveyor.io/v1beta1
        kind: Migration
        name: "{{ item.result.metadata.name }}"
        namespace: "{{ cutover_namespace }}"
        state: present
        merge_type: strategic-merge
        definition:
          spec:
            resume: true
      loop: "{{ migration_results.results }}"
      loop_control:
        loop_var: item
