---
- name: Start cutover based on Migration Plan name in OpenShift
  hosts: localhost
  gather_facts: no

  vars:
    openshift_namespace: openshift-mtv
    migration_plan_name: test-cutover13         # Set this to the name of your MigrationPlan
    migration_cr_name: cutover-{{ migration_plan_name }}-{{ ansible_date_time.epoch }}

  tasks:
    - name: Trigger cutover Migration CR
      community.kubernetes.k8s:
        state: present
        namespace: "{{ openshift_namespace }}"
        definition:
          apiVersion: migration.openshift.io/v1alpha1
          kind: Migration
          metadata:
            name: "{{ migration_cr_name }}"
          spec:
            plan: "{{ migration_plan_name }}"
            stage: false
            quiescePods: true
            keepAnnotations: true
            cutover: true

    - name: Wait for Migration to complete (cutover)
      community.kubernetes.k8s_info:
        api_version: migration.openshift.io/v1alpha1
        kind: Migration
        namespace: "{{ openshift_namespace }}"
        name: "{{ migration_cr_name }}"
      register: migration_status
      retries: 20
      delay: 30
      until: >
        migration_status.resources[0].status.conditions | selectattr('type', 'equalto', 'Succeeded') | selectattr('status', 'equalto', 'True') | list | length > 0

    - name: Show successful cutover message
      debug:
        msg: "Cutover for migration plan '{{ migration_plan_name }}' completed successfully."

