---
- name: Send dummy data to Zabbix from AAP
  hosts: localhost
  gather_facts: false

  vars:
    zabbix_url: "http://193.7.1.225"           
    zabbix_api_user: "Admin"
    zabbix_api_pass: "zabbix"
    zabbix_host: "Migration Automation"
    zabbix_item_key: "ansible.test.data"
    zabbix_value: "Test from AAP"
    zabbix_timestamp: "{{ lookup('pipe', 'date -u +%s') }}"

  tasks:
    - name: Authenticate to Zabbix API
      uri:
        url: "{{ zabbix_url }}/zabbix/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_api_user }}"
            password: "{{ zabbix_api_pass }}"
          id: 1
        return_content: true
        status_code: 200
      register: zabbix_login

    - name: Send dummy data to Zabbix
      uri:
        url: "{{ zabbix_url }}/zabbix/api_jsonrpc.php"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "sender.data"
          params:
            host: "{{ zabbix_host }}"
            data:
              - key: "{{ zabbix_item_key }}"
                value: "{{ zabbix_value }}"
                clock: "{{ zabbix_timestamp }}"
          auth: "{{ zabbix_login.json.result }}"
          id: 2
        return_content: true
        status_code: 200
      register: zabbix_push

    - name: Show result
      debug:
        var: zabbix_push.json
