---
- name: Send Ansible event to Zabbix using API
  hosts: localhost
  gather_facts: false

  vars:
    zabbix_api_url: "http://193.7.1.225/zabbix/api_jsonrpc.php"
    zabbix_user: "Admin"
    zabbix_pass: "zabbix"
    zabbix_host: "Migration Automation"
    zabbix_item_key: "ansible.event"
    event_message: "This is a test event from Ansible AAP."

  tasks:

    - name: Get auth token
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        return_content: true
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "user.login"
          params:
            username: "{{ zabbix_user }}"
            password: "{{ zabbix_pass }}"
          id: 1
      register: login_response

    - name: Set auth token
      set_fact:
        zabbix_auth_token: "{{ login_response.json.result }}"

    - name: Send data to Zabbix
      uri:
        url: "{{ zabbix_api_url }}"
        method: POST
        return_content: true
        headers:
          Content-Type: "application/json"
        body_format: json
        body:
          jsonrpc: "2.0"
          method: "history.create"
          params:
            host: "{{ zabbix_host }}"
            key: "{{ zabbix_item_key }}"
            value: "{{ event_message }}"
          auth: "{{ zabbix_auth_token }}"
          id: 2
      register: send_response

    - name: Show response
      debug:
        var: send_response.json
