- name: Read CSV and create migration plans
  hosts: localhost
  gather_facts: false
  vars:
    source_provider_name: "vmware"
    destination_provider_name: "host"
    mtv_namespace: "openshift-mtv"
    network_map_name: "test-networkmap"
    storage_map_name: "test-storagemap"

  tasks:

    - name: Read raw CSV file
      ansible.builtin.slurp:
        src: migration_plan.csv
      register: raw_csv

    - name: Decode and split CSV lines
      set_fact:
        csv_lines: "{{ raw_csv.content | b64decode | split('\n') | select('match', '.*[^,]+.*') | list }}"

    - name: Parse CSV to list of dicts
      set_fact:
        csv_parsed: >-
          {{
            csv_lines[1:] | map('split', ',') |
            map('zip', csv_lines[0] | split(',')) |
            map('items') | map('list') |
            map('dict') | list
          }}

    - name: Loop through parsed data to create migration plans
      loop: "{{ csv_parsed }}"
      loop_control:
        label: "{{ item['RHOS Name'] }}"
      block:

        - name: Create migration plan for {{ item['RHOS Name'] }}
          kubernetes.core.k8s:
            state: present
            definition:
              apiVersion: forklift.konveyor.io/v1beta1
              kind: Plan
              metadata:
                name: "{{ item['Plan Name'] }}"
