- name: Load and parse migration_plan.csv without using community.general
  hosts: localhost
  gather_facts: false
  vars:
    csv_path: "migration_plan.csv"  

  tasks:

    - name: Read CSV content (base64)
      slurp:
        src: "{{ csv_path }}"
      register: raw_csv

    - name: Ensure CSV content was read correctly
      debug:
        msg: "{{ raw_csv.content | b64decode }}"

    - name: Decode and split CSV into lines (without splitlines)
      set_fact:
        csv_lines: "{{ raw_csv.content | b64decode | regex_findall('.*') }}"

    - name: Extract CSV headers
      set_fact:
        csv_headers: "{{ csv_lines[0].split(',') | map('trim') | list }}"

    - name: Convert CSV rows into list of dicts (rows → key:value using headers)
      set_fact:
        migration_data: >-
          {{
            csv_lines[1:] |
            map('split', ',') |
            map('map', 'trim') |
            map('zip', csv_headers) |
            map('list') |
            map('dict') |
            list
          }}

    - name: Debug final parsed migration_data
      debug:
        var: migration_data
