- name: Load and parse migration_plan.csv without using community.general
  hosts: localhost
  gather_facts: false
  vars:
    csv_path: "migration_plan.csv"   # 👈 Update this path as needed

  tasks:
    - name: Read the CSV file as base64 content
      slurp:
        src: "{{ csv_path }}"
      register: raw_csv

    - name: Decode and split lines
      set_fact:
        {{ raw_csv.content | b64decode | regex_findall('.*') }}

    - name: Extract CSV header
      set_fact:
        csv_headers: "{{ csv_lines[0].split(',') | map('trim') | list }}"

    - name: Convert CSV rows into list of dicts
      set_fact:
        migration_data: >-
          {{
            csv_lines[1:] |
            map('split', ',') |
            map('map', 'trim') |
            map('zip', csv_headers) |
            map('list') |
            map('dict') |
            list
          }}

    - name: Debug the final parsed migration data
      debug:
        var: migration_data
