- name: Read CSV and create migration plans
  hosts: localhost
  gather_facts: false
  vars:
    source_provider_name: "vmware"
    destination_provider_name: "host"
    mtv_namespace: "openshift-mtv"
    network_map_name: "test-networkmap"
    storage_map_name: "test-storagemap"

  tasks:

    - name: Read CSV file
      ansible.builtin.slurp:
        src: migration_plan.csv
      register: raw_csv

    - name: Decode CSV content
      set_fact:
        csv_lines: "{{ raw_csv.content | b64decode | split('\n') | reject('equalto', '') | list }}"

    - name: Convert CSV to list of dicts
      set_fact:
        csv_parsed: >-
          {{
            csv_lines[1:] | map('split', ',') |
            map('zip', csv_lines[0] | split(',')) |
            map('dict') | list
          }}

    - name: Include task to create migration plan for each row
      include_tasks: create_plan.yaml
      loop: "{{ csv_parsed }}"
      loop_control:
        loop_var: item
