- name: Load and parse migration_plan.csv in AAP-safe way
  hosts: localhost
  gather_facts: false
  vars:
    csv_path: "migration_plan.csv"  # ✅ Must be inside project directory

  tasks:

    - name: Read CSV content (base64)
      slurp:
        src: "{{ csv_path }}"
      register: raw_csv

    - name: Decode and split CSV into lines (portable method)
      set_fact:
        csv_lines: "{{ raw_csv.content | b64decode | regex_findall('.*') }}"

    - name: Extract CSV headers
      set_fact:
        csv_headers: "{{ csv_lines[0].split(',') | map('trim') | list }}"

    - name: Initialize empty migration_data list
      set_fact:
        migration_data: []

    - name: Convert each CSV row to dictionary and append to migration_data
      set_fact:
        migration_data: "{{ migration_data + [dict(csv_headers | zip(row | split(',') | map('trim') | list))] }}"
      loop: "{{ csv_lines[1:] }}"
      loop_control:
        loop_var: row

    - name: Show parsed migration data
      debug:
        var: migration_data
