---
- name: VM Migration Plan with Predefined NetworkMap and StorageMap
  hosts: localhost
  gather_facts: false
  vars:
    vcenter_hostname: "10.60.38.189"
    vcenter_username: "vcenter.testing@ngcs-lab.local"
    vcenter_password: "tyv-XFZ1ehb0wcy!tdw"

    mtv_namespace: "openshift-mtv"
    source_provider_name: "vmware"
    destination_provider_name: "host"

    selected_vm_id: "vm-30730"
    selected_vm_name: "rhel-8-clone"

    # Pre-created mappings
    network_map_name: "vmware-d49vh"
    storage_map_name: "vmware-5n78s"

  tasks:

    - name: Get list of all VMs in vCenter
      vmware.vmware_rest.vcenter_vm_info:
        vcenter_hostname: "{{ vcenter_hostname }}"
        vcenter_username: "{{ vcenter_username }}"
        vcenter_password: "{{ vcenter_password }}"
        vcenter_validate_certs: false
      register: vm_list

    - name: Print VM Name and VM ID
      ansible.builtin.debug:
        msg: "VM Name: {{ item.name }} | VM ID: {{ item.vm }}"
      loop: "{{ vm_list.value }}"

