---
- name: Check if migrated VMs are reachable (Linux/Windows) without community.general
  hosts: localhost
  gather_facts: false

  vars:
    # Provide comma-separated IPs from survey or CLI
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    ping_results: []

  tasks:

    - name: Check TCP reachability on port 22 and 3389 for each IP
      vars:
        ssh_check: >-
          {{
            lookup('pipe', "nc -z -w2 " ~ item ~ " 22 && echo open || echo closed")
          }}
        rdp_check: >-
          {{
            lookup('pipe', "nc -z -w2 " ~ item ~ " 3389 && echo open || echo closed")
          }}
        status_icon: >-
          {{
            ('open' in ssh_check or 'open' in rdp_check) | ternary('✅', '❌')
          }}
      set_fact:
        ping_results: "{{ ping_results + [ {'ip': item, 'status': status_icon} ] }}"
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"

    - name: Format results into a table
      set_fact:
        formatted_output: >-
          {%- set header = "| IP Address      | Ping Status |" -%}
          {%- set separator = "|------------------|-------------|" -%}
          {%- set rows = [] -%}
          {%- for item in ping_results -%}
          {%-   set _ = rows.append("| " ~ item.ip.ljust(16) ~ " | " ~ item.status.center(11) ~ " |") -%}
          {%- endfor -%}
          {{ ([header, separator] + rows) | join('\n') }}

    - name: Show reachability result table
      debug:
        msg: "{{ formatted_output }}"
