---
- name: Check if migrated VMs are reachable (Linux/Windows) using native modules
  hosts: localhost
  gather_facts: false

  vars:
    # Inject this via survey as a comma-separated string
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    ping_results: []

  tasks:

    - name: Check TCP port 22 and 3389 for each IP
      block:
        - name: Check port 22 (SSH)
          wait_for:
            host: "{{ item }}"
            port: 22
            timeout: 2
            state: started
          register: ssh_check
          ignore_errors: true

        - name: Check port 3389 (RDP)
          wait_for:
            host: "{{ item }}"
            port: 3389
            timeout: 2
            state: started
          register: rdp_check
          ignore_errors: true

        - name: Add ping result for IP
          set_fact:
            ping_results: "{{ ping_results + [ {'ip': item, 'status': ((ssh_check is succeeded) or (rdp_check is succeeded)) | ternary('✅', '❌') } ] }}"
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"

    - name: Format results into a table
      set_fact:
        formatted_output: >-
          {%- set header = "| IP Address      | Ping Status |" -%}
          {%- set separator = "|------------------|-------------|" -%}
          {%- set rows = [] -%}
          {%- for item in ping_results -%}
          {%-   set _ = rows.append("| " ~ item.ip.ljust(16) ~ " | " ~ item.status.center(11) ~ " |") -%}
          {%- endfor -%}
          {{ ([header, separator] + rows) | join('\n') }}

    - name: Show VM reachability results
      debug:
        msg: "{{ formatted_output }}"
