---
- name: Check if migrated VMs are reachable (Linux/Windows) using TCP ports
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    ping_results: []

  tasks:

    - name: Check reachability of each IP (Linux/Windows)
      vars:
        current_ip: "{{ item }}"
      block:

        - name: Check SSH (port 22) reachability
          wait_for:
            host: "{{ current_ip }}"
            port: 22
            timeout: 2
            state: started
          register: ssh_result
          ignore_errors: true

        - name: Check RDP (port 3389) reachability
          wait_for:
            host: "{{ current_ip }}"
            port: 3389
            timeout: 2
            state: started
          register: rdp_result
          ignore_errors: true

        - name: Append result for current IP
          set_fact:
            ping_results: "{{ ping_results + [ {
              'ip': current_ip,
              'status': ((ssh_result is succeeded) or (rdp_result is succeeded)) | ternary('✅', '❌')
            } ] }}"
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"

    - name: Format results into a table
      set_fact:
        formatted_output: >-
          {%- set header = "| IP Address      | Ping Status |" -%}
          {%- set separator = "|------------------|-------------|" -%}
          {%- set rows = [] -%}
          {%- for item in ping_results -%}
          {%-   set _ = rows.append("| " ~ item.ip.ljust(16) ~ " | " ~ item.status.center(11) ~ " |") -%}
          {%- endfor -%}
          {{ ([header, separator] + rows) | join('\n') }}

    - name: Show formatted reachability table
      debug:
        msg: "{{ formatted_output }}"
