---
- name: Ping test after VM migration (from survey input)
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"  # Injected via survey
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    header: "| IP Address      | Ping Status |\n|------------------|-------------|"

  tasks:
    - name: Initialize ping results
      set_fact:
        ping_results: []

    - name: Ping each IP and collect status
      shell: "ping -c 1 -W 1 {{ item }} > /dev/null 2>&1 && echo success || echo fail"
      register: ping_check
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"
      changed_when: false
      ignore_errors: true

    - name: Store formatted ping results
      set_fact:
        ping_results: "{{ ping_results + [{
          'ip': item.item,
          'status': ('✅' if item.stdout == 'success' else '❌')
        }] }}"
      loop: "{{ ping_check.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Format rows for markdown table
      set_fact:
        table_rows: >-
          {{
            ping_results |
            map('combine') |
            map('regex_replace', '^(.*)$', '| \1[ip] | \1[status] |') |
            list
          }}

    - name: Show ping result table
      debug:
        msg: "{{ header + '\n' + (table_rows | join('\n')) }}"
