- name: Ping IPs and get hostnames without SSH
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    header: "| IP Address      | Hostname         |\n|------------------|-------------------|"

  tasks:

    - name: Initialize results list
      set_fact:
        ip_results: []

    - name: Check ICMP reachability for each IP
      shell: "ping -c 1 -W 1 {{ item }}"
      register: ping_result
      ignore_errors: true
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"

    - name: Store reachable IPs
      set_fact:
        reachable_ips: >-
          {{ ping_result.results | selectattr('rc', 'eq', 0) | map(attribute='item') | list }}

    - name: Resolve hostnames for reachable IPs
      shell: "getent hosts {{ item }} | awk '{print $2}'"
      register: host_lookup
      ignore_errors: true
      loop: "{{ reachable_ips }}"
      loop_control:
        label: "{{ item }}"

    - name: Build results list
      set_fact:
        ip_results: "{{ ip_results + [ {'ip': item, 'hostname': (lookup_result.stdout | default('Unresolved')) }] }}"
      loop: "{{ host_lookup.results }}"
      loop_control:
        label: "{{ item.item }}"
      vars:
        lookup_result: "{{ item }}"

    - name: Format rows for table
      set_fact:
        table_rows: >-
          {{
            ip_results |
            map('combine') |
            map('regex_replace', '^(.*)$', '| \1[ip] | \1[hostname] |') |
            list
          }}

    - name: Display formatted results table
      debug:
        msg: "{{ header + '\n' + (table_rows | join('\n')) }}"
