- name: Add dynamic hosts based on IP list
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"

  tasks:
    - name: Add dynamic hosts to inventory
      add_host:
        name: "{{ item }}"
        ansible_host: "{{ item }}"
        groups: dynamic_targets
      loop: "{{ ip_array }}"


- name: Ping hosts and get hostnames
  hosts: dynamic_targets
  gather_facts: true
  any_errors_fatal: false

  tasks:
    - name: Ensure host is reachable
      ping:

    - name: Set hostname fact per host
      set_fact:
        ip_hostname: "{{ {'ip': inventory_hostname, 'hostname': ansible_hostname} }}"

    - name: Register hostname results
      set_fact:
        all_hostnames: "{{ all_hostnames | default([]) + [ip_hostname] }}"


- name: Display hostname table
  hosts: localhost
  gather_facts: false

  vars:
    header: "| IP Address      | Hostname         |\n|------------------|-------------------|"

  tasks:
    - name: Set up formatted table rows
      set_fact:
        table_rows: >-
          {{
            groups['dynamic_targets'] | map('extract', hostvars, 'ip_hostname') |
            select('defined') |
            map('combine') |
            map('regex_replace', '^(.*)$', '| \1[ip] | \1[hostname] |') |
            list
          }}

    - name: Print formatted hostname table
      debug:
        msg: "{{ header + '\n' + (table_rows | join('\n')) }}"
