- name: Check reachability and get hostnames (without ping)
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    header: "| IP Address      | Hostname         |\n|------------------|-------------------|"

  tasks:

    - name: Initialize results list
      set_fact:
        ip_results: []

    - name: Check TCP port (22) reachability for each IP
      wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 2
        state: started
      register: port_check
      ignore_errors: true
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"

    - name: Store reachable IPs
      set_fact:
        reachable_ips: >-
          {{ port_check.results | selectattr('rc', 'defined') | map(attribute='item') | list }}

    - name: Resolve hostnames for reachable IPs
      shell: "getent hosts {{ item }} | awk '{print $2}'"
      register: host_lookup
      ignore_errors: true
      loop: "{{ reachable_ips }}"
      loop_control:
        label: "{{ item }}"

    - name: Build results list
      set_fact:
        ip_results: "{{ ip_results + [ {'ip': item.item, 'hostname': (item.stdout | default('Unresolved')) }] }}"
      loop: "{{ host_lookup.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Format rows for table
      set_fact:
        table_rows: >-
          {{
            ip_results |
            map('combine') |
            map('regex_replace', '^(.*)$', '| \1[ip] | \1[hostname] |') |
            list
          }}

    - name: Display formatted results table
      debug:
        msg: "{{ header + '\n' + (table_rows | join('\n')) }}"
