- name: Ping check for a list of IPs and format the output
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    header: "| IP Address      | Ping Status |"
    separator: "|------------------|-------------|"

  tasks:

    - name: Initialize ping results list
      set_fact:
        ping_results: []

    - name: Perform ping check for each IP (Linux-style)
      shell: "ping -c 1 -W 1 {{ item }} >/dev/null 2>&1 && echo success || echo fail"
      register: ping_out
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"

    - name: Build result list with ✔️ or ❌
      set_fact:
        ping_results: "{{ ping_results + [ {'ip': item.item, 'status': ('✔️' if item.stdout == 'success' else '❌')} ] }}"
      loop: "{{ ping_out.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Format each row
      set_fact:
        result_rows: >-
          {{ ping_results | map(attribute='ip') | zip(ping_results | map(attribute='status')) | map('list') |
             map('join', ' | ') | map('regex_replace', '^(.*)$', '| \\1 |') | list }}

    - name: Assemble final table
      set_fact:
        final_table: "{{ [header, separator] + result_rows }}"

    - name: Show formatted ping result table
      debug:
        msg: "{{ final_table | join('\n') }}"
