- name: Ping IPs and get hostnames without SSH
  hosts: localhost
  gather_facts: false
  vars:
    ip_list: "{{ ip_list | default('') }}"
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    header: "| IP Address      | Hostname         |\n|------------------|-------------------|"

  tasks:

    - name: Initialize results list
      set_fact:
        ip_results: []

    - name: Ping each IP and try to resolve hostname
      vars:
        timeout: 2
      block:
        - name: Check ICMP reachability for {{ item }}
          wait_for:
            host: "{{ item }}"
            port: 7         # Echo service (simulates ICMP in some setups)
            timeout: "{{ timeout }}"
            state: started
          register: ping_result
          ignore_errors: true
          delegate_to: localhost

        - name: Try to resolve hostname via getent
          command: getent hosts "{{ item }}"
          register: host_lookup
          when: ping_result is not failed
          ignore_errors: true
          delegate_to: localhost

        - name: Add to result list
          set_fact:
            ip_results: "{{ ip_results + [ { 'ip': item, 'hostname': (host_lookup.stdout.split() | last | default('Unresolved')) }] }}"
          when: ping_result is not failed
      loop: "{{ ip_array }}"

    - name: Format rows for table
      set_fact:
        table_rows: >-
          {{
            ip_results |
            map('combine') |
            map('regex_replace', '^(.*)$', '| \1[ip] | \1[hostname] |') |
            list
          }}

    - name: Display formatted results table
      debug:
        msg: "{{ header + '\n' + (table_rows | join('\n')) }}"
