---
- name: Check reachability via ping and show results in table
  hosts: localhost
  gather_facts: false

  vars:
    ip_list: "{{ ip_list | default('') }}"   # Injected from survey
    ip_array: "{{ ip_list.split(',') | map('trim') | list }}"
    header: "| IP Address      | Ping Status |"
    separator: "|------------------|-------------|"
    ping_results: []

  tasks:

    - name: Ensure IP list is provided
      fail:
        msg: "No IP addresses provided via survey input."
      when: ip_list | length == 0

    - name: Ping each IP and collect status
      shell: "ping -c 2 -W 1 {{ item }} >/dev/null 2>&1 && echo success || echo fail"
      register: ping_output
      changed_when: false
      loop: "{{ ip_array }}"
      loop_control:
        label: "{{ item }}"

    - name: Build ping result list (✅ / ❌)
      set_fact:
        ping_results: "{{ ping_results + [ {'ip': item.item, 'status': ('✅' if item.stdout == 'success' else '❌') }] }}"
      loop: "{{ ping_output.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Format result rows
      set_fact:
        result_rows: >-
          {{
            ping_results |
            map(attribute='ip') |
            zip(ping_results | map(attribute='status')) |
            map('list') |
            map('join', ' | ') |
            map('regex_replace', '^(.*)$', '| \1 |') |
            list
          }}


    - name: Assemble final table
      set_fact:
        final_table: "{{ [header, separator] + result_rows }}"


    - name: Display formatted ping results table
      debug:
        msg: "{{ final_table | join('\n') }}"

