---
- name: Start Multiple Migration Plans from CSV
  hosts: localhost
  gather_facts: false

  vars:
    csv_file: "r_vm_list_to_migrate.csv"

  tasks:
    - name: Read CSV content (base64)
      slurp:
        src: "{{ csv_file }}"
      register: raw_csv

    - name: Decode and split CSV into lines
      set_fact:
        csv_lines: "{{ raw_csv.content | b64decode | regex_findall('.*') }}"

    - name: Extract CSV headers
      set_fact:
        csv_headers: "{{ csv_lines[0].split(',') | map('trim') | list }}"

    - name: Parse each row into a dictionary
      set_fact:
        all_rows: "{{ all_rows | default([]) + [dict(csv_headers | zip(row.split(',') | map('trim') | list))] }}"
      loop: "{{ csv_lines[1:] }}"
      loop_control:
        loop_var: row
      when: row.strip() != ''

    - name: Build unique plan list (Plan Name + Target Namespace)
      set_fact:
        unique_plans: "{{ unique_plans | default([]) + [ {'Plan Name': item['Plan Name'], 'Target Namespace': item['Target Namespace'], 'Cold or Warm': item['Cold or Warm']} ] }}"
      loop: "{{ all_rows }}"
      when: item['Plan Name'] not in (unique_plans | default([]) | map(attribute='Plan Name') | list)
      loop_control:
        label: "{{ item['Plan Name'] }}"

    - name: Start Migration Plan for all cold
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            generateName: "{{ item['Plan Name'] }}-migration-"
            namespace: "{{ item['Target Namespace'] }}"
          spec:
            plan:
              name: "{{ item['Plan Name'] }}"
              namespace: "{{ item['Target Namespace'] }}"
      loop: "{{ unique_plans }}"
      loop_control:
        label: "{{ item['Plan Name'] }}"
      when: 
        - (item['Cold or Warm'] | lower == 'cold' or item['Cold or Warm'] == 'COLD')
        - item['Plan Name'] is defined and item['Plan Name'] != ''
