- name: Simply read and print a CSV file
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read raw CSV file
      ansible.builtin.slurp:
        src: migration_plan.csv
      register: raw_csv

    - name: Show CSV content as plain text
      debug:
        msg: "{{ raw_csv.content | b64decode }}"
