- name: Test reading CSV with community.general.read_csv
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read CSV file
      community.general.read_csv:
        path: test_user.csv
      register: csv_output

    - name: Print parsed CSV content
      debug:
        var: csv_output.list
