- name: Read and parse CSV manually
  hosts: localhost
  gather_facts: false
  vars:
    csv_path: "test_user.csv"
  tasks:
    - name: Slurp CSV file contents
      ansible.builtin.slurp:
        src: "{{ csv_path }}"
      register: csv_file

    - name: Decode CSV content and split lines
      set_fact:
        csv_lines: "{{ csv_file['content'] | b64decode | splitlines() }}"

    - name: Parse CSV into list of dictionaries
      set_fact:
        csv_parsed: >-
          {{
            csv_lines[1:] | map('split', ',') |
            map('zip', csv_lines[0] | split(',')) |
            map('community.general.dict') | list
          }}

    - name: Display parsed CSV content
      debug:
        var: csv_parsed
