- name: Test reading CSV with community.general.read_csv
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Read CSV file
      community.general.read_csv:
        path: test_users.csv
        key: name
      register: csv_data

    - name: Print parsed CSV data
      debug:
        var: csv_data.dict
