- name: Test reading CSV with community.general.read_csv
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read users from CSV file and return a dictionary
      community.general.read_csv:
        path: test_user.csv
        key: name
      register: users
      delegate_to: localhost

    - name: Debug a specific user (e.g., dag)
      ansible.builtin.debug:
        msg: "User {{ users.dict['dag'].name }} has UID {{ users.dict['dag'].uid }} and GID {{ users.dict['dag'].gid }}"
