- name: Read and parse CSV manually
  hosts: localhost
  gather_facts: false
  vars:
    csv_path: "test_user.csv"
  tasks:
    - name: Read CSV file (base64 encoded)
      ansible.builtin.slurp:
        src: "{{ csv_path }}"
      register: csv_file

    - name: Decode and split CSV into lines
      set_fact:
        csv_lines: "{{ csv_file['content'] | b64decode | split('\n') | select('length') | list }}"

    - name: Convert CSV lines to list of dicts
      set_fact:
        csv_parsed: >-
          {{
            csv_lines[1:] | map('split', ',') |
            map('zip', csv_lines[0] | split(',')) |
            map('community.general.dict') | list
          }}

    - name: Show parsed CSV data
      debug:
        var: csv_parsed
