---
- name: Start Migration Plan
  hosts: localhost
  gather_facts: false
  vars:
    vcenter_hostname: "10.60.38.189"
    vcenter_username: "vcenter.testing@ngcs-lab.local"
    vcenter_password: "tyv-XFZ1ehb0wcy!tdw"

    mtv_namespace: "openshift-mtv"
    source_provider_name: "vmware"
    destination_provider_name: "host"

    selected_vm_id: "vm-30730"
    selected_vm_name: "rhel-9"

    network_map_name: "test-networkmap"
    storage_map_name: "test-storagemap"
    plan_name: "{{ selected_vm_name }}-vmware-test"

  tasks:  
    - name: Start Migration Plan
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            name: rhel-9-vmware-test
            namespace: openshift-mtv
          spec:
            plan:
              name: rhel-9-vmware-test
              namespace: openshift-mtv
