---
- name: Start Multiple Migration Plans from Survey
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml  # Optional external vars

  tasks:
    - name: Start Migration Plan "{{ item }}"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            generateName: "{{ item }}-migration-"
            namespace: openshift-mtv
          spec:
            plan:
              name: "{{ item }}"
              namespace: openshift-mtv
      loop: "{{ plan_names.split(',') | map('trim') | list }}"
      loop_control:
        loop_var: item
