---
- name: Start Migration Plan
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml  # External vars like mtv_namespace, etc.

  vars_prompt:
    - name: plan_names
      prompt: "Enter the comma-separated list of plan names (e.g., plan-1,plan-2)"
      private: no  # Don't hide input
      default: ""  # Default to an empty string if nothing is entered

  tasks:
    - name: Start Migration Plans
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            name: "{{ item }}"  # Use item from loop as plan name
            namespace: openshift-mtv
          spec:
            plan:
              name: "{{ item }}"  # Plan name from loop
              namespace: openshift-mtv
      loop: "{{ plan_names.split(',') }}"  # Split the input string into a list of plan names
      loop_control:
        loop_var: item
