---
- name: Start Multiple Migration Plans from CSV
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Read CSV content (base64)
      slurp:
        src: vm_list_to_migrate.csv
      register: raw_csv

    - name: Decode and split CSV into lines
      set_fact:
        csv_lines: "{{ raw_csv.content | b64decode | regex_findall('.*') }}"

    - name: Extract CSV headers
      set_fact:
        csv_headers: "{{ csv_lines[0].split(',') | map('trim') | list }}"

    - name: Parse each row into a dictionary
      set_fact:
        all_rows: "{{ all_rows | default([]) + [dict(csv_headers | zip(row.split(',') | map('trim') | list))] }}"
      loop: "{{ csv_lines[1:] }}"
      loop_control:
        loop_var: row
      when: row.strip() != ''

    - name: Extract unique plan name and target namespace pairs
      set_fact:
        unique_plans: >-
          {{
            all_rows
            | groupby('Plan Name')
            | map('last')
            | map('first')
            | map('extract', ['Plan Name', 'Target Namespace'])
            | list
          }}

    - name: Start Migration Plan for each unique Plan Name and Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            generateName: "{{ item['Plan Name'] }}-migration-"
            namespace: "{{ item['Target Namespace'] }}"
          spec:
            plan:
              name: "{{ item['Plan Name'] }}"
              namespace: "{{ item['Target Namespace'] }}"
      loop: "{{ unique_plans }}"
      loop_control:
        label: "{{ item['Plan Name'] }}"
