---
- name: Start Migration Plan
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml  # Your external variables, like namespace, etc.

  tasks:  
    - name: Start Migration Plans
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            name: "{{ item }}"  # Use the item from the loop as the plan name
            namespace: openshift-mtv
          spec:
            plan:
              name: "{{ item }}"  # Plan name from loop
              namespace: openshift-mtv
      loop: "{{ plan_names.split(',') }}"  # Split the 'plan_names' string into a list
      loop_control:
        loop_var: item
