---
- name: Start Migration Plan
  hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yaml

  tasks:  
    - name: Start Migration Plans
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: forklift.konveyor.io/v1beta1
          kind: Migration
          metadata:
            name: "{{ item }}"   # Use item as plan name
            namespace: openshift-mtv
          spec:
            plan:
              name: "{{ item }}"  # Plan name from loop
              namespace: openshift-mtv
      loop: "{{ plan_names.split(',') }}"  # Split the extra var into a list and loop over it
