---
- name: Main
  hosts: localhost
  tasks:
  - name: Load Plan
    include_vars:
      file: plan.yml 
      name: plan

  - name: Load Workload
    include_vars:
      file: workload.yml
      name: workload

  - k8s_info:
      api_version: v1
      kind: Secret
      name: privkey
      namespace: openshift-mtv
    register: ssh_credentials

  - name: Debug SSH credentials
    debug:
      var: ssh_credentials

  - name: Ensure SSH directory exists
    file:
      path: ~/.ssh
      state: directory
      mode: 0750

  - name: Create SSH key
    copy:
      dest: ~/.ssh/id_rsa
      content: "{{ ssh_credentials.resources[0].data.key | b64decode }}"
      mode: 0600

  - add_host:
      name: "{{ workload.vm.ipaddress }}"
      ansible_user: root
      groups: vms

  - name: Set Workload & Plan fact
    set_fact:
      workload: "{{ workload }}"
      plan: "{{ plan }}"
    
  - name: Show Workload info
    debug:
      msg: "{{ workload }}"

  - name: Show Plan Details
    debug:
      msg: "{{ plan }}"

- hosts: vms
  gather_facts: yes  # We need facts to determine OS type
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
  tasks:
  - name: Wait for VM to boot
    wait_for_connection:
      timeout: 600

  # RHEL Specific Tasks
  - name: Create Test File
    copy:
      dest: /tmp/post_test_rhel.txt
      content: "This is a test file on RHEL"
      mode: 0644

  - name: Run prehook command
    shell: "df -hT;ip a >>/tmp/posthookfile"
