---
# tasks file for roles/list_vms
- name: Get list of all VMs in vCenter
  vmware.vmware_rest.vcenter_vm_info:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_validate_certs: false
  register: vm_list

- name: Print VM Name and VM ID
  ansible.builtin.debug:
    msg: "VM Name: {{ item.name }} | VM ID: {{ item.vm }}"
  loop: "{{ vm_list.value }}" 
